### ISSUE TITLE
mp4 video

### ISSUE THREAD

**Issue by VicMahoney** [PeteJobi/RealEsrganUpscalerGUI#2] opened 2023-12-05 18:05 UTC
Hello! The program does not select MP4 videos, only photos are available.

**Comment by PeteJobi** [comment] 2023-12-05 19:34
Hello. Please check that FFMPEG is present in the same folder. If it's not, then you probably downloaded the "Image-only" assets folder. Please download the full assets folder [here](https://github.com/PeteJobi/RealEsrganUpscalerGUI/releases/tag/v3.0.0-assets)

**Comment by VicMahoney** [comment] 2023-12-06 15:48
@PeteJobi I downloaded this folder, now the video is loading, but after a minute of work it throws an error
system.agrumentoutofrangeException value ''-465'' is invalid for value

Upd:i installed ffmpeg in system path and after that its ok, thanks

**Comment by PeteJobi** [comment] 2023-12-06 18:46
Glad to see it works. Though I don't think the issue is ffmpeg-related. But since the original issue is resolved, I'll close this ticket. Feel free to open another if that error shows up again.

**Closed as completed by PeteJobi** 2023-12-06 18:46 UTC
